//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFCReader.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NFCReader.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NT NFC Reader.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share....
        /// </summary>
        public static string Button_share {
            get {
                return ResourceManager.GetString("Button_share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It looks that this device does not support NFC..
        /// </summary>
        public static string Error_NFC_NotSupported {
            get {
                return ResourceManager.GetString("Error_NFC_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw payload (Hex, ASCII).
        /// </summary>
        public static string HexPayload {
            get {
                return ResourceManager.GetString("HexPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text has been copied to your clipboard!.
        /// </summary>
        public static string Message_Copied {
            get {
                return ResourceManager.GetString("Message_Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NDEF Header.
        /// </summary>
        public static string NDEFHeader {
            get {
                return ResourceManager.GetString("NDEFHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected NFC tag.
        ///To see detail, swipe right..
        /// </summary>
        public static string NFC_Message_detected {
            get {
                return ResourceManager.GetString("NFC_Message_detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No NDEF record has found..
        /// </summary>
        public static string NFC_Message_error {
            get {
                return ResourceManager.GetString("NFC_Message_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone may display error message for some tags, however, please ignore it..
        /// </summary>
        public static string NFC_Message_guide {
            get {
                return ResourceManager.GetString("NFC_Message_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch to your tag..
        /// </summary>
        public static string NFC_Message_mainPage {
            get {
                return ResourceManager.GetString("NFC_Message_mainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payload (Force converted as ASCII).
        /// </summary>
        public static string Payload {
            get {
                return ResourceManager.GetString("Payload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records of Sony&apos;s camera.
        /// </summary>
        public static string SonyRecordTitle {
            get {
                return ResourceManager.GetString("SonyRecordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Title_error {
            get {
                return ResourceManager.GetString("Title_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data from your NFC tag.
        /// </summary>
        public static string Title_shareText {
            get {
                return ResourceManager.GetString("Title_shareText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Name Format.
        /// </summary>
        public static string TypeNameFormat {
            get {
                return ResourceManager.GetString("TypeNameFormat", resourceCulture);
            }
        }
    }
}
